server:
  port: ${test.server.port:7859}

regCenter:
#  serverList: localhost:2181
#  serverList: 192.168.1.191:2181
  serverList: 192.168.7.185:2181
  namespace: job-lite

orderEventJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

cartEventJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

createOrderSnJob:
  cron: 1 0 0 * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

checkSnNumberJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

sn:
  number: ${test.sn.number:10000}

url:
  syncUrl: ${test.syncUrl:http://pms.jxkj.com/jxpms-web/baseMaterialInfo/getMaterialInfoByCode}

spring:
  application:
    name: ${test.spring.application.name:provider-job-dubbo}
  dubbo:
    application.name: job-facade-consumer
    registry.address: ${test.dubbo.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${test.dubbo.protocol.port:20995}
    scan: com.kingthy.job,com.kingthy.service.impl

  redis:
    database: ${test.spring.redis.database:1}
    host: ${test.spring.redis.host:192.168.1.225}
    port: ${test.spring.redis.port:6379}
    password: ${test.spring.redis.password:myredis}
    timeout: ${test.spring.redis.timeout:0}
    pool:
      max-active: ${test.spring.redis.pool.max-active:20}
      min-idle: ${test.spring.redis.pool.min-idle:5}
      max-idle: ${test.spring.redis.pool.max-idle:10}
      max-wait: ${test.spring.redis.pool.max-wait:-1}

logging:
  level:
    com.kingthy.service.impl: ${test.com.kingthy.service.impl:info}

