server:
  port: ${dev.server.port:7859}

regCenter:
  serverList: localhost:2181
#  serverList: 192.168.7.185:2181
  namespace: job-lite

orderEventJob:
  cron: 0/100 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

cartEventJob:
  cron: 0/500 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

createOrderSnJob:
  cron: 1 0 0 * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

checkSnNumberJob:
  cron: 0/500 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=A,1=B,2=C,3=D,4=E

sn:
  number: ${dev.sn.number:10000}

url:
  syncUrl: ${dev.syncUrl:http://pms.jxkj.com/jxpms-web/baseMaterialInfo/getMaterialInfoByCode}

spring:
  application:
    name: ${dev.spring.application.name:provider-job-dubbo}
  dubbo:
    application.name: job-facade-consumer
    registry.address: ${dev.dubbo.address:zookeeper://192.168.7.185:2181}
#    registry.address: zookeeper://localhost:2181
    protocol.name: dubbo
    protocol.port: ${dev.dubbo.protocol.port:20995}
#    scan: com.kingthy.job
    scan: com.kingthy.job,com.kingthy.service.impl

  redis:
    database: ${dev.spring.redis.database:1}
    host: ${dev.spring.redis.host:192.168.1.225}
#    host: localhost
    port: ${dev.spring.redis.port:6379}
    password: ${dev.spring.redis.password:myredis}
#    password:
    timeout: ${dev.spring.redis.timeout:0}
    pool:
      max-active: ${dev.spring.redis.pool.max-active:20}
      min-idle: ${dev.spring.redis.pool.min-idle:5}
      max-idle: ${dev.spring.redis.pool.max-idle:10}
      max-wait: ${dev.spring.redis.pool.max-wait:-1}

logging:
  level:
    com.kingthy.service.impl: ${dev.com.kingthy.service.impl:info}

