server.port:  ${production.server.port}
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  application:
    name: ${production.spring.application.name:provider-order-dubbo}
  redis:
      database: ${production.spring.redis.database:1}
      host: ${production.spring.redis.host:192.168.1.225}
      port: ${production.spring.redis.port:6379}
      password: ${production.spring.redis.password:myredis}
      timeout: ${production.spring.redis.timeout:0}
      pool:
        max-active: ${production.spring.redis.pool.max-active:20}
        min-idle: ${production.spring.redis.pool.min-idle:5}
        max-idle: ${production.spring.redis.pool.max-idle:10}
        max-wait: ${production.spring.redis.pool.max-wait:-1}
  rabbitmq:
    host: ${production.rabbitmq.host:192.168.1.148}
    port: ${production.rabbitmq.port:5672}
    username: ${production.rabbitmq.username:admin}
    password: ${production.rabbitmq.password:Jxkj2016}
  dubbo:
    application.name: order-facade-consumer
    registry.address: ${production.dubbo.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${production.dubbo.protocol.port:20898}
    scan: com.kingthy.service.impl
eureka:
  client:
    serviceUrl: 
      defaultZone: ${production.eureka.client.serviceUrl.defaultZone}
  instance:
    lease-renewal-interval-in-seconds: ${production.lease-renewal-interval-in-seconds}
    lease-expiration-duration-in-seconds: ${production.lease-expiration-duration-in-seconds}
    prefer-ip-address: true
logging:
  level:
    com.kingthy.service.impl: ${production.com.kingthy.service.impl}
    com.kingthy.mapper: ${production.com.kingthy.mapper}
hystrix:
  #超时阀值，默认1000毫秒#
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
  #熔断后，相隔多长时间，发起重试，默认5000毫秒#
  command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
  #当在配置时间窗口内达到此数量的失败后，进行短路。默认20个#
  command.default.circuitBreaker.requestVolumeThreshold: 20
  #出错百分比阈值，当达到此阈值后，开始短路。默认50%#
  command.default.circuitBreaker.errorThresholdPercentage: 50
  #线程池核心线程数,默认10
  threadpool.default.coreSize: 2000
  #最大等待队列数
  threadpool.default.maxQueueSize: 2000
  #当实际线程数超过核心线程数时，线程存活时间，默认1分钟
  threadpool.default.keepAliveTimeMinutes: 1
  #允许在队列中的等待的任务数量，请求拒绝临界值，默认5
  threadpool.default.queueSizeRejectionThreshold: 5