server: 
  port:  ${test.server.port:9527}

spring:
  application:
     name: ${test.spring.application.name:provider-geometry-dubbo}

  rabbitmq:
     host: ${test.rabbitmq.host:192.168.1.148}
     port: ${test.rabbitmq.port:5672}
     username: ${test.rabbitmq.username:admin}
     password: ${test.rabbitmq.password:Jxkj2016}

  redis: 
    database: ${test.spring.redis.database:1}
    host: ${test.spring.redis.host:192.168.1.225}
    port: ${test.spring.redis.port:6379}
    password: ${test.spring.redis.password:myredis}
    timeout: ${test.spring.redis.timeout:0}
    pool:
        max-active: ${test.spring.redis.pool.max-active:20}
        min-idle: ${test.spring.redis.pool.min-idle:5}
        max-idle: ${test.spring.redis.pool.max-idle:10}
        max-wait: ${test.spring.redis.pool.max-wait:-1}

  #dubbo配置
  dubbo:
    application.name: geometry-dubbo-consumer
    registry.address: ${test.dubbo.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${test.dubbo.protocol.port:20906}
    scan: com.kingthy.service.impl

#缓存超时设置
cache:
  expire:
    #分钟
    nullValueExpire: 8

eureka:
  client:
    serviceUrl:
      defaultZone: ${test.eureka.client.serviceUrl.defaultZone:http://192.168.7.193:10000/eureka/}
  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    com.kingthy.service.impl: DEBUG

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
