server:
  port: ${dev.server.port:7858}

regCenter:
#  serverList: localhost:2181
#  serverList: 192.168.6.140:2181
  serverList: 192.168.7.185:2181
  namespace: job-lite-docking

colourIfiJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=0,1=4,2=8

styleTypeIfiJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=0,1=4,2=8

componentTypeIfiJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=0,1=4,2=8

partsTypeIfiJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=0,1=4,2=8

ifiMaterialTypeJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=0,1=4,2=8

ifiMeasureUnitJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=0,1=4,2=8

spring:
  application:
    name: ${dev.spring.application.name:provider-docking-dubbo}
  dubbo:
    application.name: docking-job-facade-consumer
    registry.address: ${dev.dubbo.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${dev.dubbo.protocol.port:20995}
    scan: com.kingthy.service.impl,com.kingthy.job

eureka:
  client:
    serviceUrl:
      #defaultZone: ${dev.eureka.client.serviceUrl.defaultZone:http://192.168.1.225:10000/eureka/}
        #defaultZone: http://eureka1:10001/eureka/,http://eureka2:10000/eureka/
#      defaultZone: ${dev.eureka.client.serviceUrl.defaultZone:http://localhost:10000/eureka/}
      defaultZone: http://localhost:10000/eureka/

  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true

logging:
  level:
    com.kingthy.service.impl: ${dev.com.kingthy.service.impl:info}