server.port:  ${dev.server.port:9321}
spring:
  application:
    name: ${dev.spring.application.name:provider-message-dubbo}
  rabbitmq:
      host: ${dev.rabbitmq.host:192.168.1.148}
      port: ${dev.rabbitmq.port:5672}
      username: ${dev.rabbitmq.username:admin}
      password: ${dev.rabbitmq.password:Jxkj2016}
      listener:
        retry:
          max-attempts: 3
          initial-interval: 30000
          max-interval: 150000
          enabled: true
          multiplier: 2.5
#        defaultRequeueRejected: false
#      dubbo配置
  dubbo:
    application.name: message-facade-consumer
    registry.address: ${dev.dubbo.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${dev.dubbo.protocol.port:20896}
    scan: com.kingthy.service.impl
eureka:
  client:
    serviceUrl:
      defaultZone: ${dev.eureka.client.serviceUrl.defaultZone:http://192.168.1.225:10000/eureka/}
  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
logging:
  level:
    com.kingthy.service.impl: error
     