server.port:  ${test.server.port:7928}

spring:
  application:
    name: ${test.spring.application.name:provider-income-dubbo}
  redis:
    database: ${test.spring.redis.database:1}
    host: ${test.spring.redis.host:192.168.1.225}
    port: ${test.spring.redis.port:6379}
    password: ${test.spring.redis.password:myredis}
    timeout: ${test.spring.redis.timeout:0}
    pool:
      max-active: ${test.spring.redis.pool.max-active:20}
      min-idle: ${test.spring.redis.pool.min-idle:5}
      max-idle: ${test.spring.redis.pool.max-idle:10}
      max-wait: ${test.spring.redis.pool.max-wait:-1}
  rabbitmq:
    host: ${test.rabbitmq.host:192.168.1.148}
    port: ${test.rabbitmq.port:5672}
    username: ${test.rabbitmq.username:admin}
    password: ${test.rabbitmq.password:Jxkj2016}
  dubbo:
    application.name: income-facade-consumer
    registry.address: ${test.dubbo.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${test.dubbo.protocol.port:20895}
    scan: com.kingthy.service.impl


eureka:
  client:
    serviceUrl:
      defaultZone: ${test.eureka.client.serviceUrl.defaultZone:http://slave1:10000/eureka/,http://slave2:10000/eureka/,http://slave3:10000/eureka/}
  instance:
    lease-renewal-interval-in-seconds: ${test.lease-renewal-interval-in-seconds:2}
    lease-expiration-duration-in-seconds: ${test.lease-expiration-duration-in-seconds:2}
    prefer-ip-address: true
logging:
  level:
    com.kingthy.service.impl: ${test.com.kingthy.service.impl:debug}
    com.kingthy.mapper: ${test.com.kingthy.mapper:error}

hystrix:
      command.default.execution.isolation.thread.timeoutInMilliseconds: ${test.command.default.execution.isolation.thread.timeoutInMilliseconds:5000}