spring:
  profiles: slave2
  application:
    name: eureka-ha
server:
  port: 10000
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slave3:10000/eureka/,http://slave1:10000/eureka/
  server:
    #关闭自我保护
    enable-self-preservation: false
    #清理无效服务的间隔时间（缺省60*1000毫秒）
#    eviction-interval-timer-in-ms: 20

