server:
  port: 7903
spring:
  application:
    name: upload-file-dubbo

  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

  redis:
      database: ${test.spring.redis.database:1}
      host: ${test.spring.redis.host:192.168.1.225}
      port: ${test.spring.redis.port:6379}
      password: ${test.spring.redis.password:myredis}
      timeout: ${test.spring.redis.timeout:0}
      pool:
        max-active: ${test.spring.redis.pool.max-active:20}
        min-idle: ${test.spring.redis.pool.min-idle:5}
        max-idle: ${test.spring.redis.pool.max-idle:10}
        max-wait: ${test.spring.redis.pool.max-wait:-1}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2


file.serverIp: http://192.168.1.217