server.port:  8699
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  application:
    name: provider-tupu-dubbo
eureka:
  client:
    serviceUrl:
      #defaultZone: http://slave1:10001/eureka/,http://slave2:10002/eureka/,http://slave3:10000/
      defaultZone: http://localhost:10000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
logging:
  level:
    com.kingthy.service.impl: DEBUG      
     